tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

brew "bitwarden-cli"
brew "fish"
brew "ghq"
brew "gibo"
brew "git"
brew "hub"
brew "jq"
brew "lab"
brew "node"
brew "openssl"
brew "pipx"
brew "python"
brew "pyenv"
brew "readline"
brew "sqlite3"
brew "tox"
brew "wget"
brew "xz"
brew "zlib"

cask "bitwarden"
cask "chromedriver"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "roon"
cask "slack"
cask "tunnelblick"
cask "vagrant"
cask "visual-studio-code"
cask "zoom"

cask "font-source-han-code-jp"
